### ISSUE TITLE
[NPC] Burrower in the great fissure area (Hellfire peninsula) not surfacing but causing combat

### ISSUE THREAD

**Issue by BrockSamson1** [Nolin7777/TBC-Bugtracker#206] opened 2019-01-28 02:11 UTC
Patch:
2.4.3

Current behaviour:
Burrowing mob in great fissure area are causing player to enter combat but not surfacing or interacting with player in any way. Unsure of ID as mob does not surface

Expected behaviour:
Mob should surface and attack player

Steps to reproduce the problem:
Stand over moving ground that indicates burrower presence in the great fissure.
![burrower malfunction](https://user-images.githubusercontent.com/46757539/51810818-453a5880-22fe-11e9-8ade-52847f8a1efa.jpg)

**Comment by Kaziner** [comment] 2019-02-12 14:01
Duplicate of ticket #50

**Closed** 2019-02-12 20:40 UTC
Labels: SmartAI
